#19Backend/container with courses
ncedu-tlt/2020_ncpr_english_lessons pull request #34
Opened 2020-07-17 13:38 UTC by artyom-astafyev

Добавил контейнер с курсами, CRUD-операции. Есть подсчет кол-ва посещений(доп. udpate-запрос, который нужно вызывать с фронта).

2020-07-19 19:40 UTC, dnsonin requested changes
Привет, Артём. 
Исправь пожалуйста, следующие замечания.

- .gitignore - переименовывать не надо - это служебный git файл. Вернуть .gitignore.
- Папка /.vs/ и весь её контент - не нужны в git, нужно убрать.
- Папка Languages.API/bin/ и весь её контент - не нужны в git, нужно убрать.
- Папка Languages.API/obj  и весь её контент - не нужны в git, нужно убрать.
- Languages.API/Api.sln не нужен, достаточно Api.csproj. Убрать Api.sln.

В остальном ОК, выглядит готовым :)

2020-07-21 10:40 UTC, artyom-astafyev commented
gitignore косячно отображался в прошлый раз, тогда пришлось поправить. Сейчас вернул, как было.
Лишний контент убрал, не нашел только папки /.vs/

2020-07-21 16:47 UTC, dnsonin submitted a review, later dismissed
Выглядит ОК.
Но 2 HTTP PUT метода выглядят странно. Потом посмотрим.

Спасибо!

2020-07-22 07:34 UTC, dnsonin approved these changes

2020-07-22 08:10 UTC, merged